ALTER SESSION SET query_tag = '{"origin":"sf_sit-is","name":"insurance_claims_prediction_regression","version":{"major":1, "minor":0},"attributes":{"is_quickstart":1, "source":"sql"}}';

-- Switch to ACCOUNTADMIN role
USE ROLE ACCOUNTADMIN;

-- Create a new role for data scientists
CREATE OR REPLACE ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

-- set my_user_var variable to equal the logged-in user
SET my_user_var = (SELECT  '"' || CURRENT_USER() || '"' );

-- Grant role to current user
GRANT ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST TO USER identifier($my_user_var);

-- Create a new role for feature store producer
CREATE OR REPLACE ROLE INSURANCECLAIMSPREDICTIONREGRESSION_FS_PRODUCER;

-- Grant role to current user
GRANT ROLE INSURANCECLAIMSPREDICTIONREGRESSION_FS_PRODUCER TO USER identifier($my_user_var);

-- Create a warehouse with specified configuration
CREATE OR REPLACE WAREHOUSE INSURANCECLAIMSPREDICTIONREGRESSION_DS_WH 
    SCALING_POLICY = 'STANDARD', 
    WAREHOUSE_SIZE = 'XSMALL', 
    WAREHOUSE_TYPE = 'STANDARD', 
    AUTO_RESUME = true, 
    AUTO_SUSPEND = 60, 
    MAX_CONCURRENCY_LEVEL = 8, 
    STATEMENT_TIMEOUT_IN_SECONDS = 172800;

-- Create a database
CREATE OR REPLACE DATABASE INSURANCECLAIMSPREDICTIONREGRESSION_PROD;

-- Create schemas within the database
CREATE SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW;
CREATE SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.FS;
CREATE SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.REGISTRY;
CREATE SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ANALYTICS;
-- CREATE SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ML;

-- Create or replace a CSV file format in the RAW schema
CREATE OR REPLACE FILE FORMAT INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.CSV_INS_CLAIMS_FF 
    TYPE = 'csv'
    NULL_IF = ('NULL', 'null', '')
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1; 

-- Create or replace an S3 stage in the RAW schema
CREATE OR REPLACE STAGE INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.S3LOAD_INS_CLAIMS
    COMMENT = 'Quickstarts S3 Stage Connection',
    URL = 's3://sfquickstarts/sfguide_getting_started_with_predicting_insurance_claims_regression_model/insurance_claims_data.csv',
    FILE_FORMAT = INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.CSV_INS_CLAIMS_FF;

CREATE OR REPLACE TABLE INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.MOTOR_INSURANCE_POLICY_CLAIMS 
    (IDPOL number,
    CLAIMNB number,
    EXPOSURE double,
    AREA varchar,
    VEHPOWER varchar,
    VEHAGE number,
    DRIVAGE number,
    BONUSMALUS number,
    VEHBRAND varchar,
    VEHGAS varchar,
    DENSITY number,
    REGION varchar
   );
   
COPY INTO INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.MOTOR_INSURANCE_POLICY_CLAIMS
from @INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW.S3LOAD_INS_CLAIMS/;

-- Grant privileges on the DATABASE to the SYSADMIN and DATA SCIENTIST roles
GRANT ALL ON DATABASE INSURANCECLAIMSPREDICTIONREGRESSION_PROD TO ROLE SYSADMIN;
GRANT ALL ON DATABASE INSURANCECLAIMSPREDICTIONREGRESSION_PROD TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;


-- Grant privileges on SCHEMAS to the SYSADMIN and DATA SCIENTIST roles
GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.FS TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.FS TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ANALYTICS TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ANALYTICS TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.REGISTRY TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.REGISTRY TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

-- Grant privileges on ALL TABLES in SCHEMA to the DATA SCIENTIST role
GRANT ALL ON ALL TABLES IN SCHEMA INSURANCECLAIMSPREDICTIONREGRESSION_PROD.RAW TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

-- Create the NOTEBOOK in the ANALYTICS schema
CREATE OR REPLACE STAGE INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ANALYTICS.NOTEBOOK 
DIRECTORY = (ENABLE = TRUE) 
ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

GRANT ALL ON STAGE INSURANCECLAIMSPREDICTIONREGRESSION_PROD.ANALYTICS.NOTEBOOK TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;

-- Grant privileges on the WAREHOUSE to the SYSADMIN and DATA SCIENTIST roles
GRANT ALL ON WAREHOUSE INSURANCECLAIMSPREDICTIONREGRESSION_DS_WH TO ROLE SYSADMIN;
GRANT ALL ON WAREHOUSE INSURANCECLAIMSPREDICTIONREGRESSION_DS_WH TO ROLE INSURANCECLAIMSPREDICTIONREGRESSION_DATA_SCIENTIST;


